#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t jdc"

$L "  ____  ____  __   ____  ____        ____  ____  _  _  ___  _____  _  _ ";
$L " (_  _)( ___)(  ) (_  _)( ___)      (  _ \( ___)( \/ )/ __)(  _  )( \( )";
$L ".-_)(   )__)  )(__  )(   )__)        )(_) ))__)  \  /( (__  )(_)(  )  ( ";
$L "\____) (__)  (____)(__) (____)      (____/(____)  \/  \___)(_____)(_)\_)";

$L "Welcome to Android `getprop ro.build.version.release` / by JDCTeam";
