#!/bin/sh
# dotOS Changelog

export Changelog=Changelog.txt

if [ -f $Changelog ];
then
	rm -f $Changelog
fi

touch $Changelog

if [ "$SKIP_CHANGELOG" = "1" ] ; then
  echo "Skipped because 'SKIP_CHANGELOG' was enabled" >> $Changelog;
else
for i in $(seq 7);
do
export After_Date=`date --date="$i days ago" +%F`
k=$(expr $i - 1)
export Until_Date=`date --date="$k days ago" +%F`
echo "====================" >> $Changelog;
echo "     $Until_Date    " >> $Changelog;
echo "====================" >> $Changelog;
repo forall -pc 'git log --after=$After_Date --until=$Until_Date --pretty=tformat:"%h  %s  [%an]" --abbrev-commit --abbrev=7' >> $Changelog
echo "" >> $Changelog;
done

sed -i 's/project/ */g' $Changelog
sed -i 's/[/]$//' $Changelog
fi

cp $Changelog $OUT/system/etc/
cp $Changelog $OUT/
rm $Changelog 
